### ISSUE TITLE
Readme small items

### ISSUE THREAD

**Issue by whit1206** [dod-ccpo/atat#1133]
There are a few quick suggestions:

1. The readme lists the "scripts" directory but you call it "/script" in the tree structure. The original "one script to rule them all" also uses /script, so I would suggest you just change the readme.
2. Python version 3.7.4 is the current latest on OSX using brew. Your documentation says 3.7.3 is required. Can this be changed to >= instead of ==? or can I only use that version of Python?

**Comment by JRNPW** [comment]
Question 1 transferred to Pivotal Tracker board to be addressed.

We're checking into the decision about Python version. It's been a while since it was set at 3.7.3.

**Comment by JRNPW** [comment]
The first issue was addressed with PR #1135 

We're holding off on the second because our Tech Lead, Dan, has been out of the office several days this week.

**Comment by JRNPW** [comment]
@whit1206 I haven't forgotten the question about Python versions. Dan, the Tech Lead, and I moved our chat about that and some other issues to Thursday this week, given all the activity that surrounds the Award and the start of the integration phase.
