### ISSUE TITLE
Requested readme additions

### ISSUE THREAD

**Issue by whit1206** [dod-ccpo/atat#1160]
It would be helpful to devs new to AT-AT to have some more details in the readme. Please add the following sections:

1. Config options (where they are, how to choose which config file, and common config options or config files the dev may want to be aware of. For instance how do I simulate a non-dev env?)
2. Error logging/common problems (where are the error logs by default? what are common errors and workarounds when standing this up?). One problem I faced when standing this up was I was able to stand it up locally and run it using "script/server", but I then tried to standup using docker compose it says it worked, but all I got was an "Internal Server Error" page and no error code or reference to error log was made. 
3. Version number (this will be helpful for bug tracking on github and for non-dev users and devs to know what version is deployed). Would we consider even adding a bug submit link to github or whatnot within the application?

**Comment by JRNPW** [comment]
Converted to [Pivotal Tracker card](https://www.pivotaltracker.com/story/show/169544608)

**Comment by whit1206** [comment]
@JRNPW I was hoping to add a # 4 to that list (sorry for the late addition, I would be happy to move to another ticket if you like):
4. Simplify cloning the repo portion - It doesn't appear to actually have any submodules in the code and I would also mention that if they use the ssh method, they will need to have already trusted their ssh cert with github or use the https download method. Does this make sense

**Comment by JRNPW** [comment]
I updated the existing card.
I get your point about Github. I think we generally assume that folks have experience with Github, but it's helpful to be reminded that's not always the case.
