### ISSUE TITLE
Create Deployment guide

### ISSUE THREAD

**Issue by whit1206** [dod-ccpo/atat#1166]
The readme sort of covers how to deploy, but it is not very clear what model to use or the full steps necessary for deployment.

This ticket is to create a deployment guide that covers:
1. Easy to follow steps necessary to deploy for local dev, staging, and production
2. Any configurations/setup needed for each of these deployments
3. Any best practices and/or security considerations around AT-AT's deployment  (prod mostly)
4. How to seed the data for the first launch, especially in production
5. How would one perform an update if already deployed to that environment
6. What needs to be set up to support the CI/CD pipeline that is planned

Note: this is partially related to the previous readme additions ticket, but it calls out creating a separate and more thorough deployment guide. It is suggested this also be a markdown file in its own directory and linked to from the readme so both are easy to consume. 

Some of the issues to maybe consider when writing this document:
1. What cloud or related technology stack items will be used? Can we link to them with a simple description so people can brush up on those if they haven't used them before (like the readme does a good job now of)
2. What are the minimal steps required to get AT-AT deployed to that env the first time and thereafter?
3. What future improvements would we like to add? For MVP we might have to do more manually but what are the thoughts around automation and other future tech items to look at as well?

**Comment by JRNPW** [comment]
Converted to a [Pivotal Tracker Card](https://www.pivotaltracker.com/story/show/169582268)
