### ISSUE TITLE
Use longer user names in mocks and testing

### ISSUE THREAD

**Issue by geekychristine** [dod-ccpo/atat#1224]
Just a small test data suggestion: use more inclusive names for Users in designs and testing -- it could really help solve for annoying future design and development problems sooner, create more robust design and components, and set a great example for testing best practices. 

Some examples of gotchas/questions I've encountered in the past that could be prevented/more easily answered with better names from the get-go:

- Does this person’s really long name break our nicely-tailored layout that really only accommodated for folks like "John Smith"? 
- Should we allow user's names to wrap in table rows, or do we truncate their names? If we truncate, what are the negative implications of that (accessibility, sorting, searching)?
- This person has special characters in their name. Are we using UTF-8 encoding? Do the fonts we've selected include those characters?
- Do our font size hierarchies need to be adjusted to accommodate more verbose content coming from a CMS or other data store?

Keep up the awesome work! 😄

**Comment by JRNPW** [comment]
Thanks, @geekychristine. I transferred your notes above into a story card in Pivotal Tracker, which we use for planning and tracking our sprints. It will be prioritized and addressed in our usual sprint planning sessions. I can't guarantee that there will be much more feedback on this issue until it makes it into a sprint.
