### ISSUE TITLE
Should we rename this repo to just be "at-at"?

### ISSUE THREAD

**Issue by jordangov** [dod-ccpo/atat#130]
Seems like this is going to be the main codebase, and the project is "AT-AT" ... so?

**Comment by ddsdevon** [comment]
Maybe... though we will probably spin at least a couple of microservices back out.
If we are voting on names, I wouldn't mind putting atat- as the first part of all the repo names, just so if the CCPO puts other stuff in the org it is easy to see whats what.

**Comment by jordangov** [comment]
That's not a bad idea...
